FROM python:3.10

WORKDIR /app

RUN apt-get update \
    && apt-get install -y build-essential gcc g++ imagemagick cmake \
    && rm -rf /var/lib/apt/lists/* \
    && pip install dlib==19.19.0

ENV POETRY_HOME=/etc/poetry

RUN mkdir -p $POETRY_HOME \
    && curl -sSL https://install.python-poetry.org | python3 -

ENV PATH=${POETRY_HOME}/bin:$PATH

RUN poetry config virtualenvs.create false 
