name: Base Docker image push

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile-base'
      - '.github/workflows/base-docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker build . --file Dockerfile-base --tag ericovis/python3-10-dlib:latest
    - name: Add a tag
      run: docker tag ericovis/python3-10-dlib:latest ericovis/python3-10-dlib:$(date +%s)
    - name: Login
      run: docker login -u ericovis -p ${DOCKER_HUB_TOKEN}
    - name: Push
      run: docker push -a ericovis/python3-10-dlib
