name: Base Docker image push

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: export DOCKER_TAG="ericovis/python3-10-dlib:$(date +%s)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile-base --tag ${DOCKER_TAG}
    - name: Add latest tag
      run: docker tag ${DOCKER_TAG} ericovis/python3-10-dlib:latest
    - name: Docker login
      run: docker login -u ericovis -p ${DOCKER_HUB_TOKEN}
    - name: Docker push
      run: docker push ${DOCKER_TAG} ericovis/python3-10-dlib:latest
