name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'poetry.lock'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: docker-compose run web pytest -vvv
