name: Tests

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'poetry.lock'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'poetry.lock'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - run: chmod +x ./cc-test-reporter
    - run: ./cc-test-reporter before-build
    - run: docker-compose run web coverage run pytest -vvv && ./cc-test-reporter after-build --exit-code $?
      env:
        CC_TEST_REPORTER_ID: $CODE_CLIMATE_TOKEN
