name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'poetry.lock'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'poetry.lock'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: $CODE_CLIMATE_TOKEN
      with:
        coverageCommand: docker-compose run web coverage run pytest -vvv 
